services:
  - type: web
    name: parhamshariat
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: NEXT_PUBLIC_SITE_URL
        value: https://parhamshariat.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://wthgmbwsqlgugefwxfhk.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
